environments:
- name: acceptance
  provider: ecs-fargate
  loadbalancer:
      hostedzone: devops.evisions.com
      name: demo
      certificate: 62468c03-83b5-450a-80e1-b31da691c07a
- name: production
  provider: ecs-fargate
  loadbalancer:
      hostedzone: devops.evisions.com
      name: prod
      certificate: 62468c03-83b5-450a-80e1-b31da691c07a

templates:
  mu-r53-example: 
    Resources:
      DNS: 
        Type: "AWS::Route53::HostedZone"
        Properties: 
          HostedZoneConfig: 
            Comment: "My hosted zone for iris.devops.evisions.com"
          Name: "iris.devops.evisions.com"
#          VPCs: 
#            - 
#              VPCId: "vpc-4262b338"
#              VPCRegion: "us-east-1"
          HostedZoneTags: 
            - 
              Key: "dept"
              Value: "devops"
            - 
              Key: "project"
              Value: "learn_cfn"
 
service:
  port: 80
  pathPatterns:
  - /*
  pipeline:
    notify:
    - surfnbrain@gmail.com

tags:
  'test-environment-acceptance':
    dept: devops
    project: muLearning
